services:
  db:
    image: mysql:8.3
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
    depends_on:
      db: 
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    ports:
      - 8000:80
    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_started
    working_dir: /var/www/html

volumes:
  db_data:

